// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxLP31JfFILnLAUmgV8PcWwWSCWhCIriQ',
    appId: '1:1050449415335:web:23eef87db1b96e46579f82',
    messagingSenderId: '1050449415335',
    projectId: 'do-lk-10',
    authDomain: 'do-lk-10.firebaseapp.com',
    storageBucket: 'do-lk-10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiKpqwhr-0W1wZ-vQ1Phf5v0Nv-n5tv04',
    appId: '1:1050449415335:android:fd34e04e61d9c499579f82',
    messagingSenderId: '1050449415335',
    projectId: 'do-lk-10',
    storageBucket: 'do-lk-10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSOR_gYmdma2IEAXpuCPng2XmxpbZ5B0A',
    appId: '1:1050449415335:ios:bdeb8082a1a05a44579f82',
    messagingSenderId: '1050449415335',
    projectId: 'do-lk-10',
    storageBucket: 'do-lk-10.firebasestorage.app',
    iosBundleId: 'com.example.untitled6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSOR_gYmdma2IEAXpuCPng2XmxpbZ5B0A',
    appId: '1:1050449415335:ios:bdeb8082a1a05a44579f82',
    messagingSenderId: '1050449415335',
    projectId: 'do-lk-10',
    storageBucket: 'do-lk-10.firebasestorage.app',
    iosBundleId: 'com.example.untitled6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxLP31JfFILnLAUmgV8PcWwWSCWhCIriQ',
    appId: '1:1050449415335:web:2bbdcff5007e21c7579f82',
    messagingSenderId: '1050449415335',
    projectId: 'do-lk-10',
    authDomain: 'do-lk-10.firebaseapp.com',
    storageBucket: 'do-lk-10.firebasestorage.app',
  );
}
